global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "$Company"
    static_configs:
      - targets: ["localhost:9182"]
        labels:
          instance: "$ServerName"

  - job_name: "$ServerName"
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "127.0.0.1:9115"

remote_write:
  - url: "$URL"
